package entity.moveyStuff;

import entity.BattleStats;
import entity.Move;
import entity.Pokemon;
import entity.StatType;

// Damage move behaviour framework was generated by ChatGPT
public class StatsBasedDamageBehaviour implements MoveBehaviour {

    @Override
    public void execute(Move move,
                        Pokemon user,
                        Pokemon target,
                        BattleStats userBattleStats,
                        BattleStats targetBattleStats) {
        if (hitSucceeds(move, userBattleStats, targetBattleStats)) {
            int damage = calculateDamage(user, target);
            target.takeDamage(damage);
        }
    }

    private boolean hitSucceeds(Move move,
                                BattleStats userBattleStats,
                                BattleStats targetBattleStats) {
        return ((float) move.getMoveAccuracy() / 100 *
                userBattleStats.getStat(StatType.ACCURACY) *
                targetBattleStats.getStat(StatType.EVASION) >
                (Math.random() * 256) / 255 );
    }

    private int calculateDamage(Move move,
                                BattleStats userBattleStats,
                                BattleStats targetBattleStats) {
        if (move.getMoveClass() == "physical") {
            return //Damage calculation from pokemon wiki
        } else if (move.getMoveClass() == "special") {
            return // Damage calculation from pokemon wiki
        }
    }
}

