package entity;

/**
    This class represents the base stats of a pokemon at a certain level. These stats
are not related to a Pokemons state in combat and are final because the base attributes
of a Pokemon at a specific level never change. The only time the stats of a Pokemon
are permanently altered is when the Pokemon increases in level, after which a new
 Stats object should be made as the information in the current one becomes obsolete.
    For example, for a Pikachu at level one, the Stats object that the Pokemon would
 refer to initially would represent the values of a Pikachu at level one. After leveling up,
 the stat values of a Pikachu at level one would lose their importance and a
 new Stats object that represents the attributes of a Pikachu at level two would
 need to be created.
    In the greater context of this project as a whole, the information contained
 within this class serves as the baseline information for the BattleStats class
 whose attributes will be used in all combat calculations. Also, given the limited
 scope and timeframe of this project, a levelling system will not be implemented.
 All considerations related to levelling up Pokemon is simply to account for possible
 future extensions of the program.

 Design Considerations:
    Stats has been separated from being primitive values in the Pokemon class to
being contained within their own class. The reasoning for doing so is as follows:
    - SRP: Previously, the Pokemon class was not just responsible for managing
    the behaviour of Pokemon entities but also stat logic. Separating the two
    ensures that classes have clearly defined and comprehensible goals
    - Separating the Pokemon and  Stats classes ensures the stat values are
    encapsulated. This ensures that any requested changes to the stats are governed
    by the methods of this class and cannot be altered by cheaters.

     A builder creational pattern has been used for this class primarily to make
 instantiation far more comprehensible and explicit. Another minor justification
 is to make the addition of a new stat easier, as there is precedent for such a
 change in the Pokemon franchise: the specialAttack and specialDefense stats
 were a singular stat - Special - in generation one of Pokemon.

    The reason that two different stats classes are used within the program is
 to align with the SRP. The class BattleStats is responsible for the stats of
 a Pokemon in the context of a battle while this class is responsible for persistent
 attributes of a Pokemon outside of battle.
 */
public class BaseLevelStats {
    private final int maxHp;
    private final int attack;
    private final int defense;
    private final int specialAttack;
    private final int specialDefense;
    private final int speed;

    private BaseLevelStats(Builder builder) {
        this.maxHp = builder.maxHp;
        this.attack = builder.attack;
        this.defense = builder.defense;
        this.specialAttack = builder.specialAttack;
        this.specialDefense = builder.specialDefense;
        this.speed = builder.speed;
    }

    //Method created and suggested by ChatGPT for easier code debugging
    @Override
    public String toString() {
        return String.format("HP:%d ATK:%d DEF:%d SP.ATK:%d SP.DEF:%d SPD:%d",
                maxHp, attack, defense, specialAttack, specialDefense, speed);
    }


    public int getMaxHp() {return this.maxHp;}
    public int getAttack() {return attack;}
    public int getDefense() {return defense;}
    public int getSpecialDefense() {return specialDefense;}
    public int getSpecialAttack() {return specialAttack;}
    public int getSpeed() {return speed;}


    //Builder framework generated by ChatGPT
    public static class Builder {

        private int maxHp;
        private int attack;
        private int defense;
        private int specialAttack;
        private int specialDefense;
        private int speed;

        public Builder maxHp(int maxHp) {
            this.maxHp = maxHp;
            return this;
        }

        public Builder attack(int attack) {
            this.attack = attack;
            return this;
        }

        public Builder defense(int defense) {
            this.defense = defense;
            return this;
        }

        public Builder specialAttack(int specialAttack) {
            this.specialAttack = specialAttack;
            return this;
        }

        public Builder specialDefense(int specialDefense) {
            this.specialDefense = specialDefense;
            return this;
        }

        public Builder speed(int speed) {
            this.speed = speed;
            return this;
        }

        // Build final immutable stats object
        public BaseLevelStats build() {
            return new BaseLevelStats(this);
        }
    }
}
